/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUsernameRouteImport } from './routes/user.$username'
import { Route as PodcastIdRouteImport } from './routes/podcast.$id'
import { Route as PersonSlugRouteImport } from './routes/person.$slug'
import { Route as EpisodeIdRouteImport } from './routes/episode.$id'
import { Route as AdminHiveRouteImport } from './routes/admin.hive'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUsernameRoute = UserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastIdRoute = PodcastIdRouteImport.update({
  id: '/podcast/$id',
  path: '/podcast/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonSlugRoute = PersonSlugRouteImport.update({
  id: '/person/$slug',
  path: '/person/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeIdRoute = EpisodeIdRouteImport.update({
  id: '/episode/$id',
  path: '/episode/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHiveRoute = AdminHiveRouteImport.update({
  id: '/admin/hive',
  path: '/admin/hive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/showcase': typeof ShowcaseRoute
  '/admin/hive': typeof AdminHiveRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/person/$slug': typeof PersonSlugRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/showcase': typeof ShowcaseRoute
  '/admin/hive': typeof AdminHiveRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/person/$slug': typeof PersonSlugRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/following': typeof FollowingRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/showcase': typeof ShowcaseRoute
  '/admin/hive': typeof AdminHiveRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/person/$slug': typeof PersonSlugRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/user/$username': typeof UserUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/following'
    | '/search'
    | '/settings'
    | '/showcase'
    | '/admin/hive'
    | '/episode/$id'
    | '/person/$slug'
    | '/podcast/$id'
    | '/user/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/following'
    | '/search'
    | '/settings'
    | '/showcase'
    | '/admin/hive'
    | '/episode/$id'
    | '/person/$slug'
    | '/podcast/$id'
    | '/user/$username'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/following'
    | '/search'
    | '/settings'
    | '/showcase'
    | '/admin/hive'
    | '/episode/$id'
    | '/person/$slug'
    | '/podcast/$id'
    | '/user/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  FollowingRoute: typeof FollowingRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ShowcaseRoute: typeof ShowcaseRoute
  AdminHiveRoute: typeof AdminHiveRoute
  EpisodeIdRoute: typeof EpisodeIdRoute
  PersonSlugRoute: typeof PersonSlugRoute
  PodcastIdRoute: typeof PodcastIdRoute
  UserUsernameRoute: typeof UserUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$username': {
      id: '/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof UserUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/$id': {
      id: '/podcast/$id'
      path: '/podcast/$id'
      fullPath: '/podcast/$id'
      preLoaderRoute: typeof PodcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/person/$slug': {
      id: '/person/$slug'
      path: '/person/$slug'
      fullPath: '/person/$slug'
      preLoaderRoute: typeof PersonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$id': {
      id: '/episode/$id'
      path: '/episode/$id'
      fullPath: '/episode/$id'
      preLoaderRoute: typeof EpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hive': {
      id: '/admin/hive'
      path: '/admin/hive'
      fullPath: '/admin/hive'
      preLoaderRoute: typeof AdminHiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  FollowingRoute: FollowingRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ShowcaseRoute: ShowcaseRoute,
  AdminHiveRoute: AdminHiveRoute,
  EpisodeIdRoute: EpisodeIdRoute,
  PersonSlugRoute: PersonSlugRoute,
  PodcastIdRoute: PodcastIdRoute,
  UserUsernameRoute: UserUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
